"""The database layer: the same SQL has to behave the same on SQLite and on PostgreSQL.

These run on whichever backend the suite runs on (SQLite by default, PostgreSQL with
TEST_DATABASE_URL), so each assertion is checked against both.
"""
import pytest

from testbench import db, storage, users
from .conftest import sqlite_only


@pytest.fixture
def app(projects_dir, make_app):
    return make_app(projects_dir)


def test_placeholders_are_rewritten_outside_string_literals_only():
    assert db.translate("SELECT ? WHERE a = ?", True) == "SELECT %s WHERE a = %s"
    # A ? or % inside a literal is data, not a placeholder.
    assert db.translate("SELECT 'why?' , '50%' WHERE x LIKE ?", True) == "SELECT 'why?' , '50%%' WHERE x LIKE %s"
    assert db.translate("SELECT 'it''s ?' , ?", True) == "SELECT 'it''s ?' , %s"
    assert db.translate("SELECT '100%'", False) == "SELECT '100%'"     # no params: sent as written


def test_ddl_is_made_valid_for_postgres():
    ddl = db.postgres_ddl("id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT UNIQUE COLLATE NOCASE, at REAL")
    assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
    assert "COLLATE" not in ddl and "DOUBLE PRECISION" in ddl


def test_rows_read_by_name_and_by_position(app):
    with app.app_context():
        conn = storage.connect("example")
        pid = db.insert(conn, "INSERT INTO participants (identity, created_at, last_seen_at) VALUES (?, ?, ?)",
                        ("ABCD-1234", "2026-01-01", "2026-01-01"))
        row = conn.execute("SELECT id, identity FROM participants WHERE id = ?", (pid,)).fetchone()
        assert row["id"] == row[0] == pid
        assert row["identity"] == row[1] == "ABCD-1234"
        assert list(row.keys()) == ["id", "identity"]
        assert dict(zip(row.keys(), row)) == {"id": pid, "identity": "ABCD-1234"}


def test_insert_returns_increasing_ids(app):
    with app.app_context():
        conn = storage.connect("example")
        ids = [db.insert(conn, "INSERT INTO participants (identity, created_at, last_seen_at) VALUES (?, ?, ?)",
                         (f"P-{i}", "t", "t")) for i in range(3)]
        assert ids == sorted(ids) and len(set(ids)) == 3


def test_greatest_keeps_the_larger_value_in_an_upsert(app):
    with app.app_context():
        conn = storage.connect("example")
        conn.execute("CREATE TABLE IF NOT EXISTS g (k TEXT PRIMARY KEY, v INTEGER)")
        sql = (f"INSERT INTO g (k, v) VALUES (?, ?) ON CONFLICT(k) DO UPDATE SET "
               f"v = {db.greatest(conn, 'g.v', 'excluded.v')}")
        for v in (5, 3, 9, 1):
            conn.execute(sql, ("a", v))
        assert conn.execute("SELECT v FROM g WHERE k = 'a'").fetchone()[0] == 9


def test_booleans_are_stored_as_integers(app):
    with app.app_context():
        conn = storage.connect("example")
        pid = db.insert(conn, "INSERT INTO participants (identity, created_at, last_seen_at) VALUES (?, ?, ?)",
                        ("B-1", "t", "t"))
        sid = db.insert(conn, "INSERT INTO sessions (participant_id, module_id, step, started_at) VALUES (?, ?, ?, ?)",
                        (pid, "m", "s", "t"))
        conn.execute("INSERT INTO task_results (session_id, position, variant, task_id, gave_up, updated_at) "
                     "VALUES (?, ?, ?, ?, ?, ?)", (sid, 1, "A", "t1", True, "t"))
        assert conn.execute("SELECT gave_up FROM task_results").fetchone()[0] == 1


def test_integrity_errors_are_one_type(app):
    with app.app_context():
        conn = storage.connect("example")
        conn.execute("INSERT INTO participants (identity, created_at, last_seen_at) VALUES (?, ?, ?)", ("DUP", "t", "t"))
        with pytest.raises(db.IntegrityError):
            conn.execute("INSERT INTO participants (identity, created_at, last_seen_at) VALUES (?, ?, ?)",
                         ("DUP", "t", "t"))
        # The connection is still usable after the failure (autocommit on PostgreSQL).
        assert conn.execute("SELECT COUNT(*) FROM participants").fetchone()[0] == 1


def test_studies_cannot_see_each_others_rows(app):
    with app.app_context():
        a, b = storage.connect("alpha"), storage.connect("beta")
        a.execute("INSERT INTO participants (identity, created_at, last_seen_at) VALUES (?, ?, ?)", ("A-1", "t", "t"))
        a.commit()
        assert a.execute("SELECT COUNT(*) FROM participants").fetchone()[0] == 1
        assert b.execute("SELECT COUNT(*) FROM participants").fetchone()[0] == 0


def test_drop_study_removes_it_and_the_next_connect_starts_empty(app):
    with app.app_context():
        conn = storage.connect("gone")
        conn.execute("INSERT INTO participants (identity, created_at, last_seen_at) VALUES (?, ?, ?)", ("G-1", "t", "t"))
        conn.commit()
        assert db.study_exists("gone")
        db.drop_study("gone")
        assert not db.study_exists("gone")
        assert storage.connect("gone").execute("SELECT COUNT(*) FROM participants").fetchone()[0] == 0


def test_platform_tables_live_apart_from_studies(app):
    with app.app_context():
        users.create_user("someone@example.org", "Someone", "a-long-password")
        study = storage.connect("example")
        with pytest.raises(Exception):
            study.execute("SELECT COUNT(*) FROM users").fetchone()


def test_health_reports_the_database(app):
    body = app.test_client().get("/health").get_json()
    assert body["database_ok"] is True
    assert body["database"] == ("postgres" if db.is_postgres(app) else "sqlite")


@sqlite_only
def test_sqlite_files_sit_in_data_dir(app, tmp_path):
    with app.app_context():
        storage.connect("example")
        assert (tmp_path / "data" / "example.db").exists()
